version: "3"
services:

  ens-map-app-server:
    container_name: ens-map-app-server
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --port 3003
    volumes:
      - ./data:/data/db
    ports:
      - "3003:3003"